// supabase/functions/checkout/index.ts
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
// Using npm specifier for Deno to load the Node.js midtrans-client package
import midtransClient from "npm:midtrans-client@1.3.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req: Request) => {
  // 1. Handle CORS Preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { buyerInfo, cartItems, totalAmount } = body;

    // Validate payload
    if (!buyerInfo || !cartItems || cartItems.length === 0) {
      return new Response(JSON.stringify({ error: "Invalid payload" }), { 
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } 
      });
    }

    // 2. Initialize Supabase Client with Service Role Key
    // This allows us to bypass RLS and securely execute the RPC
    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // 3. STEP 1: Call the Atomic RPC Function
    // Sending the exact payload structure required by create_order_atomic
    const { data: orderId, error: rpcError } = await supabase.rpc("create_order_atomic", {
      p_buyer_name: buyerInfo.name,
      p_buyer_email: buyerInfo.email,
      p_buyer_phone: buyerInfo.phone,
      p_shipping_address: buyerInfo.shippingAddress,
      p_total_amount: totalAmount,
      p_items: cartItems // Expected format: [{ product_id, quantity, price }]
    });

    if (rpcError || !orderId) {
      console.error("RPC Error:", rpcError);
      throw new Error("Failed to create atomic order in database");
    }

    console.log(`Order ${orderId} created successfully via atomic RPC.`);

    // 4. STEP 2: Initialize Midtrans Node.js client
    const isProduction = Deno.env.get("MIDTRANS_IS_PRODUCTION") === "true";
    const snap = new midtransClient.Snap({
      isProduction: isProduction,
      serverKey: Deno.env.get("MIDTRANS_SERVER_KEY") ?? "",
    });

    // Format items for Midtrans
    const itemDetails = cartItems.map((item: any) => ({
      id: item.product_id,
      price: item.price,
      quantity: item.quantity,
      name: item.name || "E-Book / Textbook",
    }));

    // Add convenience fee if it exists in total calculation
    const calculatedSubtotal = cartItems.reduce((acc: number, item: any) => acc + (item.price * item.quantity), 0);
    if (totalAmount > calculatedSubtotal) {
      itemDetails.push({
        id: "FEE",
        price: totalAmount - calculatedSubtotal,
        quantity: 1,
        name: "Biaya Layanan",
      });
    }

    const midtransPayload = {
      transaction_details: {
        order_id: orderId, // Using the exact UUID generated by our RPC
        gross_amount: totalAmount,
      },
      customer_details: {
        first_name: buyerInfo.name,
        email: buyerInfo.email,
        phone: buyerInfo.phone,
        shipping_address: {
          address: buyerInfo.shippingAddress,
        },
      },
      item_details: itemDetails,
    };

    // 5. STEP 3: Generate Midtrans Snap Token
    const transaction = await snap.createTransaction(midtransPayload);
    const snapToken = transaction.token;

    // 6. STEP 4: Update the orders table with the generated snap_token
    const { error: updateError } = await supabase
      .from("orders")
      .update({ midtrans_snap_token: snapToken })
      .eq("id", orderId);

    if (updateError) {
      console.error("Failed to update snap_token in DB:", updateError);
      // We don't necessarily throw here, because Midtrans already accepted it,
      // but logging is critical.
    }

    // 7. STEP 5: Return token and ID to frontend
    return new Response(
      JSON.stringify({ snapToken, orderId }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error: any) {
    console.error("Checkout Edge Function Error:", error.message);
    return new Response(
      JSON.stringify({ error: error.message || "Internal Server Error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
